control_dt: 0.02

msg_type: "hg"     # "hg" or "go"
imu_type: "pelvis"    # "torso" or "pelvis"

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"

dof29_joint2motor_idx: [0, 1, 2, 3, 4, 5, 
                         6, 7, 8, 9, 10, 11, 
                         12, 13, 14, 
                         15, 16, 17, 18, 19, 20, 21,
                         22, 23, 24, 25, 26, 27, 28
                    ]

default_angles: [ -0.312, 0.0, 0.0, 0.669, -0.33, 0.0,
                  -0.312, 0.0, 0.0, 0.669, -0.33, 0.0,
                   0.0,  0.0, 0.0,
                   0.2,  0.2, 0.0, 0.6, 0.0, 0.0, 0.0, 
                   0.2, -0.2, 0.0, 0.6, 0.0, 0.0, 0.0 ]

kps: [100, 100, 100, 150, 40, 40, 
      100, 100, 100, 150, 40, 40, 
      400, 400, 400, 
      100, 100, 50, 50, 20, 20, 20,
      100, 100, 50, 50, 20, 20, 20
         ]
kds: [2, 2, 2, 4, 2, 2, 
      2, 2, 2, 4, 2, 2, 
      5, 5, 5,
      2, 2, 2, 2, 1, 1, 1,
      2, 2, 2, 2, 1, 1, 1,
    ]


locomotion:
  policy_path: "../PBHC/logs/loco_model/model_6600.onnx"
  default_angles: [-0.1, 0.0, 0.0, 0.3, -0.2, 0.0,
                   -0.1, 0.0, 0.0, 0.3, -0.2, 0.0,
                    0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0, 0.0,  0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0, 0.0,  0.0, 0.0, 0.0]
  init_pos: [-0.1, 0.0, 0.0, 0.3, -0.2, 0.0,
             -0.1, 0.0, 0.0, 0.3, -0.2, 0.0,
              0.0, 0.0, 0.0,
              0.0, 0.0, 0.0, 0.0,  0.0, 0.0, 0.0,
              0.0, 0.0, 0.0, 0.0,  0.0, 0.0, 0.0]
  kps: [100, 100, 100, 200, 20, 20,
        100, 100, 100, 200, 20, 20,
        400, 400, 400,
        90, 60, 20, 60, 20, 20, 20, 
        90, 60, 20, 60, 20, 20, 20]
  kds: [2.5, 2.5, 2.5, 5, 0.2, 0.1,
        2.5, 2.5, 2.5, 5, 0.2, 0.1,
        5.0, 5.0, 5.0,
        2.0, 1.0, 0.4, 1.0, 1.0, 1.0, 1.0,
        2.0, 1.0, 0.4, 1.0, 1.0, 1.0, 1.0]
  obs_joint_mask: [
    true, true, true, true, true, true,      
    true, true, true, true, true, true,      
    true, true, true,                        
    true, true, true, true, true, true, true,
    true, true, true, true, true, true, true 
  ]
  output_action_mask: [
    true, true, true, true, true, true,      # 左腿 6 个关节
    true, true, true, true, true, true,      # 右腿 6 个关节
    false, false, false,                         # 腰部 3 个关节
    false, false, false, false, false, false, false,  #  腕部不控制
    false, false, false, false, false, false, false   #  腕部不控制
  ]
  num_output_actions: 12
  num_joints_obs: 29
  num_obs: 100

mimic:
  # policy_path: "../PBHC/logs/MotionTracking/walk2/exported/model_35000.onnx"
  # motion_file: "../PBHC/smpl_retarget/retargeted_motion_data/mink/walk.pkl"
  # policy_path: "../PBHC/logs/MotionTracking/shakehand3/exported/model_50000.onnx"
  # motion_file: "../PBHC/smpl_retarget/retargeted_motion_data/mink/shakehand.pkl"
  policy_path: "policy/walk_sgw.onnx"
  motion_file: "motion/walk_sgw.pkl"
  default_angles: [-0.312, 0.0, 0.0, 0.669, -0.33, 0.0,
                   -0.312, 0.0, 0.0, 0.669, -0.33, 0.0,
                   0.0,  0.0, 0.0,
                   0.2,  0.2, 0.0, 0.6, 0.0, 0.0, 0.0, 
                   0.2, -0.2, 0.0, 0.6, 0.0, 0.0, 0.0 ]

  init_pos: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
             0.08, 0.02, 0.02,
             0.29, 0.18,-0.07, 0.62, 0.0, 0.0, 0.0,  
             0.29,-0.22,-0.04, 0.60, 0.0, 0.0, 0.0]
  # init_pos: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, #only interpolate upper body
  #            0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
  #            0.03, 0.01, 0.00,
  #            0.16, 0.27, 0.03, 0.45, 0.0, 0.0, 0.0,  
  #            0.23,-0.21,-0.02, 0.64, 0.0, 0.0, 0.0]

              
  kps: [100, 100, 100, 150, 40, 40, 
        100, 100, 100, 150, 40, 40, 
        400, 400, 400, 
        100, 100, 50, 50, 20, 20, 20,
        100, 100, 50, 50, 20, 20, 20
          ]
  kds: [2, 2, 2, 4, 2, 2, 
        2, 2, 2, 4, 2, 2, 
        5, 5, 5,
        2, 2, 2, 2, 1, 1, 1,
        2, 2, 2, 2, 1, 1, 1,
      ]
  obs_joint_mask: [
    true, true, true, true, true, true,      # 左腿 6 个关节
    true, true, true, true, true, true,      # 右腿 6 个关节
    true, true, true,                         # 腰部 3 个关节
    true, true, true, true, false, false, false,  #  腕部不观测
    true, true, true, true, false, false, false   #  腕部不观测
  ]
  output_action_mask: [
    true, true, true, true, true, true,      # 左腿 6 个关节
    true, true, true, true, true, true,      # 右腿 6 个关节
    true, true, true,                         # 腰部 3 个关节
    true, true, true, true, false, false, false,  #  腕部不控制
    true, true, true, true, false, false, false   #  腕部不控制
  ]
  num_output_actions: 23
  num_joints_obs: 23
  num_obs: 76

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
frame_stack: 5
clip_action_limit: 100.0


max_cmd: [1., 0., 1]